config/routes.rb
Rails.application.routes.draw do


  devise_for :users
  root to: "homes#top"
  resources :books, only:[:new, :index, :show, :edit, :create ,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only:[:show,:edit,:index,:update,:destroy]

get '/home/about' => "homes#about", as: "about"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user

  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: {maximum:200 }

   def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
before_action :correct_book, only: [:edit, :update]

  def new
    @book=Book.new

  end
  def create
    @book=Book.new(book_params)
    @book.user_id=current_user.id
    if @book.save
      flash[:notice] = "Book was successfully created."
       redirect_to book_path(@book.id)
    else
       @books=Book.all

      render :index
    end

  end

  def index
    @book=Book.new
    @books=Book.all
  end

  def show
    @book=Book.find(params[:id])
    @user=current_user
    @book_comment=BookComment.new
  end

  def edit
    @book=Book.find(params[:id])

  end
  def update
    @book=Book.find(params[:id])
    if  @book.update(book_params)
       flash[:notice] = "Book was successfully updated."
      redirect_to book_path(@book.id)
    else

      render :edit
    end


  end

  def destroy
    @book=Book.find(params[:id])
    @book.destroy
    flash[:notice] = "Book was successfully destroyed."
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def correct_book
    @book = Book.find(params[:id])
    unless @book.user.id==current_user.id
      redirect_to books_path
    end

  end


end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<% if @book.errors.any? %>
        <%= @book.errors.count %>errors prohibited this obj from being saved:
        <ul>
          <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
<% end %>
 <div class="container">
   <div class="row">
     <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
       <h1>Editing Book</h1>
         <%= form_with model: @book do |f| %>


          <h4>Title</h4>
          <%= f.text_field :title %>

          <h4>Opinion</h4>
          <%= f.text_area :body %>
          <%= f.submit 'Update Book' %>
        <% end %>
        <%= link_to 'Show', book_path(@book.id) %>
        <%= link_to 'Back' , books_path %>
     </div>
   </div>
 </div>

app/views/books/index.html.erb
<% if @book.errors.any? %>
        <%= @book.errors.count %>件のエラーが発生しました
        <ul>
          <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
<% end %>
<div class="container px-5 px-sm-0">
  <div class="row">
    <%= render 'users/list', user: current_user %>
    <div class="col-md-8 offset-md-1">
     <h2>Books</h2>
     <table class="table table-hover table-inverse">
       <thead>
         <tr>
           <th></th>
           <th>Title</th>
           <th>Opinion</th>
           <th colspan="3"></th>
         </tr>
       </thead>
       <tbody>

       <% @books.each do |book| %>
       <tr>
         <td>
           <%= link_to user_path(book.user.id) do %>
              <%= image_tag book.user.get_profile_image %>
           <%end%>
         </td>
         <td>
           <%= link_to book_path(book.id) do %>
              <%= book.title %>
           <%end%>
         </td>
         <td>
           <%= book.body %>
         </td>
         <% if book.favorited_by?(current_user) %>
                  <td>
                    <%= link_to book_favorites_path(book), method: :delete do%>
                   
                      <i class="fas fa-heart like-btn "></i><%=book.favorites.count%>


                    <%end%>
                  </td>
                <%else%>
                <td>
                  <%= link_to book_favorites_path(book), method: :post do%>
                    <i class="fas fa-heart unlike-btn"></i><%=book.favorites.count%>
                  <%end%>
                </td>
                <%end%>
                <td><%=link_to "#{book.book_comments.count}コメント",book_path(book.id)  %></td>
       </tr>
     </tbody>
     <%end%>
   </table>
   </div>
  </div>
</div>

app/views/books/new.html.erb
<h1>New book</h1>

 <%= form_with model: @book do |f| %>

    <h4>Title</h4>
      <%= f.text_field :title %>
    <h4>Opinion</h4>
      <%= f.text_area :body %>
    <%= f.submit 'Create Book' %>
  <% end %>

app/views/books/show.html.erb
 <div class="container">
   <div class="row">
     <%= render 'users/list', user: @book.user %>
     <div class="col-md-8 offset-md-1">
       <h2>Book detail</h2>
       <table class="table">
         <tbody>
           <tr>
            <td>
              <%= image_tag @book.user.get_profile_image %> <br>
              <%= link_to @book.user.name, user_path(@book.user.id)  %>
            </td>
            <td>
              <%= @book.title %>
            </td>
            <td><%= @book.body %></td>
              <% if @book.user == current_user %>
                <td><%= link_to "Edit", edit_book_path(@book.id), method: :get %></td>
                 <td><%= link_to "Destroy", book_path(@book), method: :delete %></td>
              <% end %>


                <% if @book.favorited_by?(current_user) %>
                  <td>
                    <%= link_to book_favorites_path(@book), method: :delete do%>
                       <i class="fas fa-heart like-btn "></i><%=@book.favorites.count%>
                    <%end%>
                  </td>
                <%else%>
                <td>
                  <%= link_to book_favorites_path(@book), method: :post do%>
                     <i class="fas fa-heart unlike-btn "></i><%=@book.favorites.count%>
                  <%end%>
                </td>
                <%end%>

           </tr>
         </tbody>
       </table>
        <div>
          <p>コメント件数:<%= @book.book_comments.count %></p>
          <%@book.book_comments.each do |book_comment|%>

             <%= image_tag book_comment.user.get_profile_image %>

              <%= book_comment.comment %>
              <% if book_comment.user == current_user %>
              <div class="btn btn-outline-secondary ">
                  <%= link_to "Destroy",book_book_comment_path(book_comment.book, book_comment) , method: :delete %>
                </div>

              <br>
            <%end%>
            <%= book_comment.user.name %>
            <br>
          <%end%>
        </div>
        <div>
          <%= form_with model: [@book,@book_comment] do |f| %>
            <%= f.text_area :comment, rows: '5', placeholder:"コメント" %>
            <%= f.submit "送信する" %>
          <%end%>
        </div>
     </div>
   </div>
 </div>