config/routes.rb
Rails.application.routes.draw do


  devise_for :users
  root to: "homes#top"
  resources :books, only:[:new, :index, :show, :edit, :create ,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only:[:show,:edit,:index,:update,:destroy]

get '/home/about' => "homes#about", as: "about"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user

  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: {maximum:200 }

   def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :user_id, uniqueness: {scope: :book_id}

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  has_one_attached :profile_image
  validates :name, presence: true, length: { minimum:2, maximum: 20}, uniqueness: true
  validates :introduction, length:{maximum:50}

def get_profile_image
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [100, 100]).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top,:about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resorce)

      user_path(current_user.id) #Sign up
  end
  def after_sign_out_path_for(resorce)
    '/'
  end



  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,keys: [:email])
  end

end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    book=Book.find(params[:book_id])
   comment=current_user.book_comments.new(book_comment_params)
    # comment=current_user.book_comments.new(book_comment_params)
    # comment.user_id=current_user.id
    comment.book_id=book.id
    comment.save
    redirect_to request.referer
    # redirect_to book_path(book)
  end

  def destroy
    BookComment.find(params[:id]).destroy
    redirect_to book_path(params[:book_id])
    # redirect_to request.referer
  end


  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
before_action :correct_book, only: [:edit, :update]

  def new
    @book=Book.new

  end
  def create
    @book=Book.new(book_params)
    @book.user_id=current_user.id
    if @book.save
      flash[:notice] = "Book was successfully created."
       redirect_to book_path(@book.id)
    else
       @books=Book.all

      render :index
    end

  end

  def index
    @book=Book.new
    @books=Book.all
  end

  def show
    @book=Book.find(params[:id])
    @user=current_user
    @book_comment=BookComment.new
  end

  def edit
    @book=Book.find(params[:id])

  end
  def update
    @book=Book.find(params[:id])
    if  @book.update(book_params)
       flash[:notice] = "Book was successfully updated."
      redirect_to book_path(@book.id)
    else

      render :edit
    end


  end

  def destroy
    @book=Book.find(params[:id])
    @book.destroy
    flash[:notice] = "Book was successfully destroyed."
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def correct_book
    @book = Book.find(params[:id])
    unless @book.user.id==current_user.id
      redirect_to books_path
    end

  end


end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    book=Book.find(params[:book_id])
    favorite=current_user.favorites.new(book_id: book.id)
    favorite.save
     redirect_to request.referer
    # redirect_to book_path(book)
  end

  def destroy
    book=Book.find(params[:book_id])
    favorite=current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
     redirect_to request.referer
    # redirect_to book_path(book)

  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end


end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user, only: [:edit, :update]
  def show
    @user=User.find(params[:id])
    @books=@user.books
  end

  def index
    @users=User.all
  end

  def edit
    @user=User.find(params[:id])
  end

  def update
    @user=User.find(params[:id])
    if  @user.update(user_params)
      flash[:notice] = "User was successfully updated."
        redirect_to user_path(@user.id)
    else
      render :edit
    end

  end

  private

  def user_params
    params.require(:user).permit(:name,:introduction,:profile_image)
  end

  def correct_user
    @user = User.find(params[:id])
    unless @user.id==current_user.id
      redirect_to user_path(current_user.id)
    end

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="fontawesome-i2svg-active fontawesome-i2svg-complete"ra>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1", maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>

       <% if flash[:notice] %>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
      <% end %>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
        <div class="navbar-brand">
          <%= link_to "Bookers", '/', method: :get %>
        </div>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

          <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
            <% if user_signed_in?  %>

            <li class="nav-item">
              <%= link_to user_path(current_user.id) do %>


                 <i class="fas fa-home"></i>
                Home
                 <%end%>
            </li>
            <li class="nav-item">
              <%= link_to users_path do %>

               <i class="fas fa-users "></i>
                Users
              <%end%>

            </li>

            <li class="nav-item">
               <%= link_to books_path do %>

               <i class="fas fa-book-open"></i>
               Books
              <%end%>

            </li>

            <li class="nav-item">
              <%= link_to destroy_user_session_path, method: :delete do%>

                <i class="fas fa-sign-out-alt"></i>
                Logout
              <%end%>
            </li>

      <%else%>

         <li class="nav-item">
              <%= link_to '/' do %>

               <i class="fas fa-home"></i>
                Home
              <%end%>
            </li>
          <li class="nav-item">
            <%= link_to about_path do %>

           <i class="fas fa-link"></i>
            About
            <%end%>
          </li>

          <li class="nav-item">
            <%= link_to new_user_registration_path do %>

           <i class="fas fa-user-plus"></i>
            sign up
            <%end%>
          </li>


          <li class="nav-item">
            <%= link_to new_user_session_path do %>

            <i class="fas fa-sign-in-alt"></i>
            Login
            <%end%>

          </li>
      <%end%>

          </ul>
        </div>
        </div>


      </nav>

    </header>
    <main>
    <%= yield %>
    </main>

  </body>
</html>